### ISSUE TITLE
add e-mail address column

### ISSUE THREAD

**Issue by marado** [eliflab/European-Parliament-Open-Data#8]
This information is available on the website, but not easily extracted (or cross-referenced), so it would be useful to have also an e-mail address column here.

**Comment by eliflab** [comment]
At the moment we are not scraping the Parliament pages to extract emails or twitter accounts.
The list you are seeing here is a combination of manual research and checks + another list + a first scrape we did at the beginning of the term + network analysis to find new accounts.
This is because the list twitter accounts that you can find on the Parliament website is not complete/up to date. 
Since we are not scraping that part of the page, we do not have a list of emails at the moment. It's not very difficult to retrieve them, but publishing a list of email involves the risk of creating an instrument for spamming, which is something we don't want and something that the European Parliament is not very able to manage :) 
Anyway, this nice scraper here would work for your purpose :) https://github.com/openpolis/meps/blob/master/scraper.py

**Comment by marado** [comment]
@eliflab Understood.

Since I wanted a list of e-mail addresses from MEPs in a particular committee, I wrote this scrapper: https://github.com/marado/MEPsPerCommittee . However, the one you've just linked seems more powerful and complete, thank you.

Anyway, since there's no interest in adding e-mail addresses in this list, I'll just close this issue.

Cheers
